//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplexWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termino
    {
        public int Id { get; set; }
        public Nullable<int> Nro_Ecu { get; set; }
        public string Comparador { get; set; }
        public Nullable<decimal> Valor { get; set; }
    }
}
